#!/usr/bin/env python3
"""Regenerate assets/js/sermons-data.js from the church's YouTube feed.

The featured player on sermons.html always shows the newest upload on its own,
because it embeds the uploads playlist. This script refreshes the archive grid
below it, which is a baked snapshot of the channel's most recent uploads. Run it
whenever you want the grid to catch up:

    python3 scripts/refresh-sermons.py

YouTube's feed returns the latest 15 uploads. `published` is the upload date,
which is not always the date the sermon was preached, so the page labels it
"Posted" and lets the video title carry the service date.
"""

import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

CHANNEL_ID = "UCrfC6KdaZUdFrcIHmtJ0DbA"
FEED = f"https://www.youtube.com/feeds/videos.xml?channel_id={CHANNEL_ID}"
OUT = Path(__file__).resolve().parent.parent / "assets" / "js" / "sermons-data.js"
NS = {
    "a": "http://www.w3.org/2005/Atom",
    "yt": "http://www.youtube.com/xml/schemas/2015",
}


def js_string(value):
    """Quote a title for embedding in single-quoted JavaScript."""
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def main():
    try:
        with urllib.request.urlopen(FEED, timeout=30) as resp:
            xml = resp.read()
    except Exception as exc:
        print(f"Could not reach the YouTube feed: {exc}", file=sys.stderr)
        return 1

    root = ET.fromstring(xml)
    entries = []
    for entry in root.findall("a:entry", NS):
        vid = entry.find("yt:videoId", NS)
        title = entry.find("a:title", NS)
        published = entry.find("a:published", NS)
        if vid is None or title is None or published is None:
            continue
        entries.append({
            "id": vid.text.strip(),
            "title": re.sub(r"\s+", " ", title.text or "").strip(),
            "published": published.text[:10],
        })

    if not entries:
        print("Feed contained no videos; leaving the existing file alone.", file=sys.stderr)
        return 1

    lines = [
        "/* Archive snapshot of the church's YouTube uploads.",
        "   Generated by scripts/refresh-sermons.py, so edit that script rather",
        "   than this file. `published` is the upload date, not necessarily the",
        "   date the sermon was preached. */",
        "",
        "window.MM_SERMONS = [",
    ]
    for e in entries:
        lines.append(
            "  { id: %s, title: %s, published: %s },"
            % (js_string(e["id"]), js_string(e["title"]), js_string(e["published"]))
        )
    lines.append("];")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"Wrote {len(entries)} sermons to {OUT.relative_to(OUT.parents[2])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
